name: Docker Image CI

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 3 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Docker login to dockerhub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Docker login to github
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin

    - name: Build the Docker image
      run: |
        docker build \
          --file Dockerfile \
          --tag docker.pkg.github.com/$GITHUB_REPOSITORY/contact-form:latest \
          --tag pulkitjalan/contact-form:latest \
          .

    - name: Push the Docker image to dockerhub
      run: docker push pulkitjalan/contact-form:latest

    - name: Push the Docker image to github
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/contact-form:latest
